### ISSUE TITLE
isn't https supported?

### ISSUE THREAD

**Issue by serser** [Vladislao/proxy-supervisor-cli#1]
as indicated in the title, i tried to `curl` with https address but it errs with
```
curl: (56) Proxy CONNECT aborted
```

but when i curl HTTP address it is functioning. Is there any further update?

**Comment by Vladislao** [comment]
Hey @serser  👋

Updated the core lib which was outdated. It's fixed in version 1.1.0 and should be working fine now.

**Comment by Vladislao** [comment]
I'll close the issue for now, if you have any more questions - feel free to ask
